distribution_type = "ZUR_MIETE"

estate_types = [
    "WOHNUNG",
    "LAND_FORSTWIRTSCHAFT",
    "WOHNGEMEINSCHAFT",
    "GARAGE_STELLPLATZ",
    "GASTRONOMIE_HOTEL",
    "HALLEN_INDUSTRIEFLAECHE",
    "HAUS",
    "BUERO_PRAXISFLAECHE",
    "GRUNDSTUECK",
    "SONSTIGES",
    "LADENFLAECHE",
    "WOHNEN_AUF_ZEIT",
    "GEWERBE_GRUNDSTUECK",
    "RENDITEOBJEKT",
]

location_ids = [516424, 518004, 518044, 517940]
